
name: af-dementia-survival
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - lifelines
  - scikit-learn
  - pyarrow
  - pip
  - pip:
      - xgboost==3.0.3
      - torch
      - scikit-survival
      - pycox
      - shap
      - typer
      - pydantic
      - pytest
      - pyyaml
      - joblib
      - ruff
      - black
